const ranks=['IBO','Star','Star Prime','Star Elite','Ace','Ace Prime','Ace Elite','Ace Royal','Hero','Hero Elite','Hero Royal','Icon','Icon Elite','Icon Royal'];
const rankIndex=Object.fromEntries(ranks.map((x,i)=>[x,i]));
const uni=[[0,0,0,0,0],[5,0,0,0,0],[7,0,0,0,0],[9,2,0,0,0],[10,4,0,0,0],[10,5,2,0,0],[10,6,4,0,0],[10,8,5,2,0],[10,8,5,2,2],[10,8,5,2,2],[10,8,5,2,2],[10,8,5,2,2],[10,8,5,2,2],[10,8,5,2,2]];
const fast={"Star Prime":2500,"Star Elite":5000,"Ace":8000,"Ace Prime":11000,"Ace Elite":13500};
const fixed=[0,0,0,0,0,1800,3600,4800,6000,6000,6000,6000,6000,6000];
const q=s=>document.querySelector(s), n=s=>Math.max(0,Number(q(s).value)||0), money=x=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(x);
function fill(){const options=ranks.map(r=>`<option>${r}</option>`).join('');q('#title').innerHTML=options;q('#career-title').innerHTML=options;q('#fast-rank').innerHTML=Object.keys(fast).map(r=>`<option>${r}</option>`).join('')}
function calculate(e){if(e)e.preventDefault();const ti=rankIndex[q('#title').value], out={};
 const pv=n('#retail-pv'), retailRate=pv<150?0:pv<400?3:pv<1000?5:pv<2000?8:pv<2500?10:15;out['Personal Sales Commission']=pv*38*retailRate/100;q('#retail-result').textContent=money(out['Personal Sales Commission'])+` (${retailRate}%)`;q('#retail-note').textContent=`PV tier: ${pv<150?'0–149':pv<400?'150–399':pv<1000?'400–999':pv<2000?'1,000–1,999':pv<2500?'2,000–2,499':'2,500+'} · ${pv} PV × ₹38 × ${retailRate}% = ${money(out['Personal Sales Commission'])}.`;
 const fastAmount=q('#fast-time').value==='yes'?fast[q('#fast-rank').value]:0, sponsor=q('#fast-sponsor').value==='yes'?fastAmount:0;out['Fast Start']=fastAmount;q('#fast-result').textContent=money(fastAmount);q('#fast-note').textContent=`Your bonus: ${money(fastAmount)} · Sponsor match: ${money(sponsor)} (shown for reference; not included in your total).`;
 out['Ace Royal Advancement']=(n('#ace-advances')+n('#ace-matches'))*25000;q('#ace-result').textContent=money(out['Ace Royal Advancement']);
 out.Unilevel=uni[ti].reduce((sum,rate,i)=>sum+n(`#l${i+1}`)*38*rate/100,0);q('#unilevel-result').textContent=money(out.Unilevel);q('#unilevel-note').textContent=ti===0?'IBO has no Unilevel rate. Select Star or a higher paid-as title above.':`Your rates: ${uni[ti].map((r,i)=>`L${i+1} ${r}%`).join(' · ')} · Formula: Level PV × ₹38 × rate · Total: ${money(out.Unilevel)}.`;
 out.Development=n('#dev-ace')*1800+n('#dev-prime')*3600+n('#dev-elite')*4800+n('#dev-royal')*6000;q('#development-result').textContent=money(out.Development);q('#development-note').textContent=`Ace: ${n('#dev-ace')} × ₹1,800 · Ace Prime: ${n('#dev-prime')} × ₹3,600 · Ace Elite: ${n('#dev-elite')} × ₹4,800 · Ace Royal: ${n('#dev-royal')} × ₹6,000.`;
 out['Monthly Fixed']=n('#fixed-legs')*fixed[ti];q('#fixed-result').textContent=money(out['Monthly Fixed']);q('#fixed-note').textContent=fixed[ti]?`${money(fixed[ti])} per qualifying leg for ${ranks[ti]}.`:'Your paid-as title is not eligible for the Monthly Fixed Bonus.';
 const hero=ti>=rankIndex.Hero, cap=hero?(ti-rankIndex.Hero+1)*60000:0;out['Check Match']=hero?Math.min(n('#match-ten')*.10+n('#match-fifteen')*.15,cap):0;q('#check-result').textContent=money(out['Check Match']);q('#check-note').textContent=hero?`Maximum allowed generation depth: ${ti-rankIndex.Hero+1}; your per-match cap: ${money(cap)}.`:'Hero or higher paid-as title is required.';
 out['Turbo Infinity']=hero?n('#turbo-cv')*.005:0;q('#turbo-result').textContent=money(out['Turbo Infinity']);
 const icon={none:[0,0],icon:[600000,5],elite:[1200000,8],royal:[3000000,12]}[q('#icon-rank').value], months=Math.min(n('#icon-months'),icon[1]);out.Icon=icon[1]?icon[0]/icon[1]*months:0;q('#icon-result').textContent=money(out.Icon);q('#icon-note').textContent=icon[1]?`${money(icon[0]/icon[1])} per qualified month; ${months} of ${icon[1]} entered.`:'No Icon Bonus selected.';
 q('#total').textContent=money(Object.values(out).reduce((a,b)=>a+b,0));q('#breakdown').innerHTML=Object.entries(out).map(([k,v])=>`<span>${k}: <b>${money(v)}</b></span>`).join('');}
fill();q('#calculator').addEventListener('submit',calculate);q('#calculator').addEventListener('input',calculate);q('#calculator').addEventListener('change',calculate);calculate();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
